// Generated by https://quicktype.io
export enum SupportedTranslationLocales {
  tr = 'tr',
  en = 'en',
  es = 'es',
  de = 'de',
  ru = 'ru',
  ku = 'ku',
  zza = 'zza',
  fr = 'fr',
  ar = 'ar',
  el = 'el',
  he = 'he',
  it = 'it',
  ja = 'ja'
};
