name: 'Test Report'
on:
  workflow_run:
    workflows: ['Run unit tests']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Jasmine Unit Tests
        path: 'report/test/*.xml'
        reporter: java-junit
