name: 'Run unit tests'
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test-ci
      - uses: actions/upload-artifact@v2
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: report/test/unit-test.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        if: always()
        with:
          files: |
            report/test/unit-test.xml
