name: 'Run unit tests'
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run test-ci
      - uses: actions/upload-artifact@v4
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: report/test/unit-test.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        if: always()
        with:
          files: |
            report/test/unit-test.xml
      - uses: romeovs/lcov-reporter-action@v0.4.0
        with:
          lcov-file: ./report/coverage/report-lcov/lcov.info
          github-token: ${{ github.token }}
      - uses: VeryGoodOpenSource/very_good_coverage@v2
        if: always()
        with:
          path: './report/coverage/report-lcov/lcov.info'
          min_coverage: 72
          exclude: 'karma.conf.js tailwind.config.js'
